# .github/workflows/deploy.yml
name: CI/CD for Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'  # Attempt 3.13 first
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest>=8.0.0 pytest-cov>=4.1.0 httpx>=0.27.0
      - run: pytest tests/ --cov=src --cov-report=xml -v

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main' && success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Render
        env:
          RENDER_WEBHOOK: ${{ secrets.RENDER_WEBHOOK }}
        run: |
          if [ -z "$RENDER_WEBHOOK" ]; then
            echo "Render webhook secret is missing!"
            exit 1
          fi
          curl -X POST -H "Authorization: Bearer $RENDER_WEBHOOK" $RENDER_WEBHOOK