name: Deploy to Render
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Trigger Render Deploy
        run: curl -X POST -d '' ${{ secrets.RENDER_WEBHOOK }}
        env:
          RENDER_WEBHOOK: ${{ secrets.RENDER_WEBHOOK }}